Add schedule API and refactor info/config/stat apis in DownloadStation
hacf-fr/synologydsm-api pull request #3
Opened 2020-11-27 13:34 UTC by sylvaindd

2021-09-12 20:20 UTC, mib1185 requested changes
Hi @sylvaindd,
thanks for contributing 👍 
Please rebase your branch to the current `master` and furthermore add a description to this PR, what does it do, what does it add.
Last but not least, please take care of the commits below.

regards,
Michael

2021-09-12 20:20 UTC, mib1185 commented on src/synology_dsm/api/download_station/__init__.py
> +    def set_schedule_config(self, enabled: bool = None, emule_enabled: bool = None):
set defaults to `False`

2021-09-12 20:20 UTC, mib1185 commented on src/synology_dsm/api/download_station/__init__.py
> +    def update_info(self):
what is the intention of this dedicated update method?
Those the user is forced to do an manually initial update before info can be accessed

2021-09-12 20:20 UTC, mib1185 commented on src/synology_dsm/api/download_station/__init__.py
> +    def update_config(self):
what is the intention of this dedicated update method?
Those the user is forced to do an manually initial update before config data can be accessed

2021-09-12 20:20 UTC, mib1185 commented on src/synology_dsm/api/download_station/__init__.py
> +        self._config = self._dsm.get(self.INFO_API_KEY, "GetConfig")["data"]
- this could cause KeyError, in case _dsm.get() was unsuccessful
- prior result was not restricted to content of `data`

2021-09-12 20:20 UTC, mib1185 commented on src/synology_dsm/api/download_station/__init__.py
> +            "data"
this could cause KeyError, in case _dsm.get() was unsuccessful

2021-09-12 20:20 UTC, mib1185 commented on src/synology_dsm/api/download_station/__init__.py
> +    def update_schedule_config(self):
what is the intention of this dedicated update method?
Those the user is forced to do an manually initial update before schedule config data can be accessed

2021-09-12 20:20 UTC, mib1185 commented on README.rst
> +        api.download_station.set_schedule_config(True, False)
```suggestion
        api.download_station.set_schedule_config(enabled=True, emule_enabled=False)
```

2021-09-12 20:20 UTC, mib1185 commented on src/synology_dsm/api/download_station/__init__.py
> +    def update_stat(self):
what is the intention of this dedicated update method?
Those the user is forced to do an manually initial update before stat data can be accessed

2021-09-12 20:20 UTC, mib1185 commented on src/synology_dsm/api/download_station/__init__.py
> +        self._stat = self._dsm.get(self.STAT_API_KEY, "GetInfo")["data"]
- this could cause KeyError, in case _dsm.get() was unsuccessful
- prior result was not restricted to content of `data`

2025-02-09 14:02 UTC, Giga77 commented
repository not maintained

2025-02-09 14:02 UTC, closed without merging